services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - taskdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskdb:5432/taskdb
      - SPRING_DATASOURCE_USERNAME=nurlantr
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  taskdb:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nurlantr
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: taskdb